Ql. What is the difference between Ordinal Encoding and Label Encoding? Provide an example of when you might choose one over the other.

Label Encoding is used for variables where ranking and ordinal is not important. Whereas we can use Ordinal encoding where we think ranking is important to consider.

Example - Educational Qualification  - (SSLC,Diplomo,B.E,M.E, Phd)
In label encoding it is ranked as B.E - 1 Diplomo - 2 M.E - 3, Phd - 4, SSLC - 5
Here SSLC gets higher numerical value and creates confusion.

Where as ordinal encoding we can rank as   SSLC - 1, Diplomo - 2,B.E - 3, M.E - 4, Phd - 5

Q2. Explain how Target Guided Ordinal Encoding works and provide an example of when you might use it in a machine learning project.

Target Guided Ordinal encoding is used to encode categorical variable based on their relationship with target variable. When we have list of sales employees whose daily sales value is given in the column. To get their consolidated individual score we can use target Guided average value.

Q3.Define covariance and explain why it is important in statistical analysis. How is covariance calculated?

Covariance in statistics measures the extent to which two variables vary linearly. 
It reveals whether two variables move in the same or opposite directions.
Cov(x,y) =  ∑ ((x-x')(y-y')) / N-1

Q4. For a dataset with the following categorical variables: Color (red, green, blue), Size (small, medium, large), and Material {wood, metal, plastic), perform label encoding using Python's scikit-learn library. Show your code and explain the output.

In [8]:
from sklearn import preprocessing
import pandas as pd
df = pd.DataFrame({
    'color': ['red', 'green', 'blue'],
    'Size':['small','medium','large'],
    'material':['wood','metal','plastic']
})

# label_encoder object knows 
# how to understand word labels.
label_encoder = preprocessing.LabelEncoder()
  
# Encode labels in column 'species'.
df['color']= label_encoder.fit_transform(df['color'])
df['Size']= label_encoder.fit_transform(df['Size']) 
df['material']= label_encoder.fit_transform(df['material']) 
print(df['color'].unique())
print(df['Size'].unique())
print(df['material'].unique())

[2 1 0]
[2 1 0]
[2 0 1]


Q5. Calculate the covariance matrix for the following variables in a dataset: Age, Income, and Education level. Interpret the results.

In [10]:
df = pd.DataFrame({
    'Age': [20,30,45,50],
    'Income':[12000,11000,25000,35000],
    'Education_level':[3,2,1,2]
})
df.cov()

Age        Income  Education_level
Age                 189.583333  1.454167e+05        -8.333333
Income           145416.666667  1.309167e+08     -4333.333333
Education_level      -8.333333 -4.333333e+03         0.666667

Q6. You are working on a machine learning project with a dataset containing several categorical variables, including "Gender" {Male/Female), "Education Level" {High School/Bachelor's/Master's/PhD), and "Employment Status" {Unemployed/Part-Time/Full-Time).Which encoding method would you use for each variable, and why?

For Gender we will use binary/nominal encoding as there are only 2 categories.
Educational level - Ordinal encoding - to have rank for each degrees
Employment status - One Hot encoding to have categories without any rank preferances

Q7. You are analyzing a dataset with two continuous variables  "Weather" and "Humidity" and two categorical variables,"Weather conditions"(Sunny/Cloudy/Rainy) and "Wind direction"(North/South/East/West).Calculate the covariance between each pair of variables and intrepert the results.

In [23]:
import numpy as np
import pandas as pd 
#Working on 1D
data = {'Weather' : np.random.randint(30,40,12),
"Humidity" : np.random.randint(80,95,12),
"Weather_condition" : np.tile(('Sunny','Cloudy','Rainy'),4),
"Wind_direction" : np.tile(('North','south','East','West'),3)}

data = pd.DataFrame(data)
print(data)
data.cov()

    Weather  Humidity Weather_condition Wind_direction
0        31        90             Sunny          North
1        31        94            Cloudy          south
2        39        85             Rainy           East
3        38        80             Sunny           West
4        33        94            Cloudy          North
5        31        81             Rainy          south
6        35        94             Sunny           East
7        34        86            Cloudy           West
8        31        83             Rainy          North
9        39        88             Sunny          south
10       39        80            Cloudy           East
11       37        92             Rainy           West


/tmp/ipykernel_77/3176313003.py:11: FutureWarning: The default value of numeric_only in DataFrame.cov is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  data.cov()


Weather   Humidity
Weather   11.787879  -5.045455
Humidity  -5.045455  30.568182